Repository falcosecurity/falcoctl, pull requests merged in 2019-11, with the labels that each got.

#41 Add ability to limit generated rules to namespaces
  cmd/psp_conv.go
  pkg/converter/psp/converter.go
  pkg/converter/psp/k8s_psp_rules_template.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#45 Interface for processes
  process/interface.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note, size/M

#46 Update appsv1beta2 -> appsv1
  pkg/kubernetes/falco.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none, size/S

#49 Add cleanup for cr, crb and auditsink
  pkg/kubernetes/falco.go
Labels: approved, area/cli, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/S
