Repository falcosecurity/falcoctl, pull requests merged in 2019-10, with the labels that each got.

#16 update(OWNERS): adding leodido and fntlnz to approvers
  OWNERS
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#17 new: apache 2.0 license (fixes #12)
  LICENSE
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note, size/L

#15 update: fix dependencies and go modules
  .gitignore
  cmd/deleteFalco.go
  cmd/installFalco.go
  cmd/root.go
  go.mod
  go.sum
  pkg/cli/env.go
Labels: approved, area/cli, area/library, dco-signoff: yes, kind/bug, kind/cleanup, lgtm, release-note, size/L

#10 Fixing error
  kubernetes/audit.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#23 Add mstemm as reviewer/approver
  OWNERS
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note, size/XS

#25 Add a prefix to all generated lists/rules
  cmd/psp_conv.go
  pkg/converter/psp/converter.go
  pkg/converter/psp/k8s_psp_rules_template.go
Labels: approved, area/library, dco-signoff: yes, kind/cleanup, lgtm, release-note, size/L

#28 Make the annotations for psp->rules optional
  pkg/converter/psp/converter.go
  pkg/converter/psp/k8s_psp_rules_template.go
Labels: approved, area/library, dco-signoff: yes, kind/cleanup, lgtm, release-note, size/M

#31 build: allow falcoctl to be built on non-linux machines by disabling the probe loader on GOOS != linux
  cmd/probe_install.go
  cmd/probe_install_linux.go
Labels: approved, area/cli, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#32 fix: not releasing docker images for falcoctl
  release.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#35 Parse PSPs strictly, disallowing unknown fields
  pkg/converter/psp/converter.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#36 Limit syscall activity for psp rules to containers
  pkg/converter/psp/k8s_psp_rules_template.go
Labels: approved, area/cli, dco-signoff: yes, kind/bug, lgtm, release-note, size/S

#37 fix(cmd): falco version is mandatory (and has no default)
  cmd/probe_install_linux.go
Labels: approved, area/cli, dco-signoff: yes, kind/bug, kind/cleanup, lgtm, release-note, size/S

#38 update: prerun check for install probe command
  cmd/probe_install_linux.go
Labels: approved, area/cli, dco-signoff: yes, kind/bug, kind/cleanup, lgtm, release-note-none, size/XS
