Repository falcosecurity/falcoctl, pull requests merged in 2020-01, with the labels that each got.

#55 update: add leogr to OWNERS file
  OWNERS
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#54 fix(cmd): typo in install tls command
  cmd/install_tls.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#58 Adding basic README.md content
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note, retest-not-required-docs-only, size/M

#60 Removing ds.yaml
  ds.yaml
Labels: approved, area/library, dco-signoff: yes, kind/cleanup, lgtm, release-note, size/M

#63 refactored cmd package inline with go idiomatic practices
  cmd/convert.go
  cmd/convert_psp.go
  cmd/delete.go
  cmd/delete_falco.go
  cmd/install.go
  cmd/install_falco.go
  cmd/install_probe.go
  cmd/install_probe_linux.go
  cmd/install_rule.go
  cmd/install_rule_linux.go
  cmd/install_tls.go
  cmd/install_tls_linux.go
  cmd/root.go
  main.go
Labels: approved, area/cli, dco-signoff: yes, kind/cleanup, kind/feature, lgtm, release-note-none, size/L
