Repository falcosecurity/falcoctl, pull requests merged in 2022-09, with the labels that each got.

#141 fix(pusher): retrieve only the index and not all the layers
  pkg/oci/pusher/pusher.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/library, area/cli, size/XS

#137 vote: update(OWNERS): add new maintainers and reviewers
  OWNERS
Labels: dco-signoff: yes, lgtm, approved, kind/documentation, size/XS

#148 update(CI/build): build falcoctl binaries without using goreleaser
  .github/workflows/integration.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#150 update(cmd): check if registry is reachable before interacting with it
  cmd/internal/utils/validate.go
  cmd/registry_login.go
  cmd/registry_pull.go
  cmd/registry_push.go
  pkg/output/output.go
Labels: dco-signoff: yes, lgtm, size/L, approved, area/cli

#153 update(CI): change branch name from master to main in the integration workflow
  .github/workflows/integration.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#152 Create README.md for `gh-pages`
  README.md
Labels: dco-signoff: yes, lgtm, kind/documentation, size/XS

#156 build(Makefile): correct default branch
  Makefile
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/library, size/XS

#154 new(pkg/index): index normalization func
  pkg/index/index.go
  pkg/index/index_test.go
Labels: dco-signoff: yes, lgtm, size/L, approved, kind/feature, area/library

#155 new(pkg/index): read an index from file
  cmd/artifact_search.go
  pkg/index/index.go
Labels: dco-signoff: yes, lgtm, approved, kind/feature, area/library, size/M

#158 chore(pkg): fix a couple of typos
  pkg/artifact/artifact.go
  pkg/oci/types.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/library, size/XS

#160 fix: create an index with consistent state also when fetching it
  cmd/index_add.go
  cmd/index_update.go
  pkg/index/fetch.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, area/library

#161 fix(cmd/utils): support connection checking for remote registries without authentication
  cmd/internal/utils/validate.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/M
