Repository falcosecurity/falcoctl, pull requests merged in 2022-11, with the labels that each got.

#176 feature(cmd): add new global flag --disable-styling
  cmd/artifact_install.go
  cmd/internal/utils/validate.go
  cmd/root.go
  cmd/testdata/help.txt
  cmd/testdata/noargsnoflags.txt
  cmd/testdata/wrongflag.txt
  go.mod
  go.sum
  pkg/options/common_options.go
  pkg/output/output.go
  pkg/output/output_test.go
  pkg/output/tracker.go
Labels: dco-signoff: yes, lgtm, approved, kind/feature, area/cli, size/M

#178 update(ci): use -ldflags="-s -w" when building falcoctl
  .github/workflows/integration.yaml
  .goreleaser.yml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#180 new(CI): build docker images for linux amd64/arm64
  .github/workflows/docker-image.yaml
  .github/workflows/release.yaml
  .goreleaser.yml
  Makefile
  build/Dockerfile
Labels: dco-signoff: yes, lgtm, approved, size/M

#182 refactor(cmd): remove duplicated code when creating pullers and pushers
  cmd/artifact_install.go
  cmd/internal/utils/registry.go
  cmd/registry_pull.go
  cmd/registry_push.go
  pkg/oci/puller/puller.go
  pkg/oci/pusher/pusher.go
  pkg/oci/pusher/pusher_test.go
  pkg/output/tracker.go
Labels: dco-signoff: yes, lgtm, size/L, approved, kind/cleanup, area/cli

#183 fix(build): use new-style GCI CLI
  Makefile
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/tests, size/XS

#184 update(output): add new methods to the printer
  pkg/output/output.go
Labels: dco-signoff: yes, lgtm, approved, area/library, size/M

#186 chore(artifact/install): move default paths for plugins and rulesfiles to internal/config package
  internal/artifact/install/install.go
  internal/config/config.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/cleanup, area/cli
