Repository falcosecurity/falcoctl, pull requests merged in 2022-12, with the labels that each got.

#187 update(internal/utils): return full path of the extracted files in ExtractTarGz func
  internal/artifact/install/install.go
  internal/utils/extract.go
Labels: dco-signoff: yes, size/S, lgtm, approved, area/library

#188 update(output/tracker): return a nil tracker if the printer is nil
  pkg/output/tracker.go
Labels: dco-signoff: yes, lgtm, approved, area/library, size/XS

#190 update(CI): add floating tags to docker image based on major and minor version numbers of a release
  .github/workflows/docker-image.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#192 fix(pkg): create repo with functional options and fix main branch error
  pkg/oci/puller/puller.go
  pkg/oci/repository.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/library, size/XS

#193 chore: improve error messages in Login and ClientForRegistry
  internal/registry/login/login.go
  internal/utils/registry.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#194 docs: switch ref and file in push short usage
  internal/registry/push/push.go
Labels: dco-signoff: yes, lgtm, approved, kind/documentation, area/cli, size/XS

#196 chore: use default tag concurrency equal to 1
  pkg/oci/pusher/pusher.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/library, size/XS

#197 refactor(oci/client): avoid yet another wrapper for the oci client
  internal/utils/registry.go
  pkg/oci/authn/client.go
  pkg/oci/platforms.go
  pkg/oci/puller/puller.go
  pkg/oci/pusher/pusher.go
  pkg/oci/registry/registry.go
  pkg/oci/repository/repository.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/library, area/cli, size/M

#198 fix: correctly remove temp files when pushing
  pkg/oci/pusher/pusher.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, area/library

#199 fix(pkg/oci/repository): do not error when parsing semver tags that do not strictly adhere to semver
  pkg/oci/repository/repository.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/library, size/XS

#202 chore(pkg/oci): fix typo in function name
  pkg/oci/types.go
Labels: dco-signoff: yes, lgtm, approved, area/library, size/XS
