Repository falcosecurity/falcoctl, pull requests merged in 2022-10, with the labels that each got.

#164 chore(pkg): remove dead code
  pkg/oci/pusher/pusher.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/library, size/XS

#166 chore(cmd): fix comment about artifact install
  cmd/artifact_install.go
Labels: dco-signoff: yes, lgtm, approved, kind/documentation, area/cli, size/XS

#171 new(pkg): introduce a function to list available platforms for a give…
  pkg/oci/platforms.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#169 chore: rename `install tls` command to `tls install` to be compliant with new naming convention
  cmd/root.go
  cmd/testdata/help.txt
  cmd/testdata/noargsnoflags.txt
  cmd/testdata/wrongflag.txt
  cmd/tls.go
  cmd/tls_install.go
Labels: dco-signoff: yes, size/S, lgtm, approved

#175 Kcl/update readme
  README.md
Labels: dco-signoff: yes, lgtm, size/L, approved, area/examples
