Repository falcosecurity/falcoctl, pull requests merged in 2023-01, with the labels that each got.

#204 fix(linting): remove hugeParam warning
  pkg/oci/pusher/options.go
Labels: dco-signoff: yes, lgtm, approved, area/library, size/XS

#203 fix(pkg/ogi): allow the alternatives when setting a dependency in the artifact config
  pkg/oci/types.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/library, size/XS

#206 fix(ci): use main branch instead of master in codeql workflow
  .github/workflows/codeql-analysis.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#208 chore: don't use logrus as logger
  go.mod
  pkg/install/tls/generator.go
  pkg/oci/authn/credentialstore.go
  pkg/oci/pusher/pusher.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/library, area/cli, size/M

#207 chore: use const when possible
  internal/artifact/follow/follow.go
  internal/registry/pull/pull.go
  internal/registry/push/push.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/cleanup, area/cli

#209 update: add alias ls to artifact list command
  internal/artifact/list/artifact_list.go
Labels: dco-signoff: yes, lgtm, approved, kind/feature, area/cli, size/XS

#213 fix: falco is returning a string for all versions
  internal/artifact/follow/follow.go
  internal/config/config.go
  internal/follower/follower.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#214 fix: create config file directory if needed
  internal/config/config.go
Labels: dco-signoff: yes, lgtm, approved, area/library, size/XS

#215 docs: rename purpose of the tool
  cmd/root.go
Labels: dco-signoff: yes, lgtm, approved, kind/documentation, size/XS

#218 fix: update test data
  cmd/testdata/help.txt
  cmd/testdata/noargsnoflags.txt
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/XS

#217 fix: use a move function that copies content of a file if rename fails
  internal/follower/follower.go
  internal/utils/move.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/library, size/M

#216 update: add retry logic when retrieving falco versions
  internal/artifact/follow/follow.go
Labels: dco-signoff: yes, lgtm, size/L, approved, kind/feature, area/library

#225 fix(follower): correctly handle context cancelation in follower
  internal/artifact/follow/follow.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/XS

#226 chore(internal): fixed a wrong log.
  internal/follower/follower.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, size/XS

#227 refactor: move commands from internal to cmd
  cmd/artifact/artifact.go
  cmd/artifact/doc.go
  cmd/artifact/follow/doc.go
  cmd/artifact/follow/follow.go
  cmd/artifact/info/doc.go
  cmd/artifact/info/info.go
  cmd/artifact/install/deps.go
  cmd/artifact/install/deps_test.go
  cmd/artifact/install/doc.go
  cmd/artifact/install/install.go
  cmd/artifact/list/artifact_list.go
  cmd/artifact/list/doc.go
  cmd/artifact/search/artifact_search.go
  cmd/artifact/search/doc.go
  cmd/index/add/add.go
  cmd/index/add/doc.go
  cmd/index/doc.go
  cmd/index/index.go
  cmd/index/list/doc.go
  cmd/index/list/list.go
  cmd/index/remove/doc.go
  cmd/index/remove/remove.go
  cmd/index/update/doc.go
  cmd/index/update/update.go
  cmd/registry/auth/auth.go
  cmd/registry/auth/basic/basic.go
  cmd/registry/auth/basic/doc.go
  cmd/registry/auth/doc.go
  cmd/registry/auth/oauth/doc.go
  cmd/registry/auth/oauth/oauth.go
  cmd/registry/doc.go
  cmd/registry/pull/doc.go
  cmd/registry/pull/pull.go
  cmd/registry/push/doc.go
  cmd/registry/push/push.go
  cmd/registry/registry.go
  cmd/root.go
  cmd/tls/doc.go
  cmd/tls/install/doc.go
  cmd/tls/install/install.go
  cmd/tls/tls.go
  cmd/version/doc.go
  cmd/version/version.go
  cmd/version/version_suite_test.go
  cmd/version/version_test.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/cli, size/M

#228 fix: ensure extracted files are put inside dest dir
  internal/utils/extract.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#229 fix(cmd): SIGSEGV on "falcoctl version"
  cmd/root.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/XS

#231 fix(follower): do not make assumptions on data retrieved from version endpoint
  cmd/artifact/follow/follow.go
  internal/follower/follower.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/M

#230 fix(pusher): automatically add latest only if no other tag was specified
  pkg/oci/pusher/pusher.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, area/library

#234 fix(cmd): arg missing in usage message of registry auth oauth
  cmd/registry/auth/oauth/oauth.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/XS

#237 fix(version): correctly set falcoctl version at build time
  .github/workflows/docker-image.yaml
  .github/workflows/integration.yaml
  .github/workflows/release.yaml
  .goreleaser.yml
  Makefile
  build/Dockerfile
Labels: dco-signoff: yes, lgtm, size/L, approved, kind/bug

#235 fix(internal): error handling with no artifacts
  cmd/artifact/install/install.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/cleanup, area/cli

#241 update(config): remove follower's default config values
  internal/config/config.go
Labels: dco-signoff: yes, size/S, lgtm, approved, area/cli

#242 fix(internal): wrong config file name used
  internal/config/config.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/XS
