Repository falcosecurity/falcoctl, pull requests merged in 2023-02, with the labels that each got.

#245 docs(README.md): added artifact follow documentation
  README.md
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/documentation

#250 fix: use index cache in artifact commands
  cmd/artifact/info/info.go
  cmd/artifact/list/artifact_list.go
  cmd/artifact/search/artifact_search.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#248 docs(README.md): added documentation of cache mechanism
  README.md
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/documentation

#249 doc: add simple ascii art
  cmd/root.go
  cmd/testdata/help.txt
  cmd/testdata/noargsnoflags.txt
Labels: dco-signoff: yes, lgtm, approved, kind/documentation, area/cli, size/M

#254 update: use mark flags as mutually exclusive for cron and every
  cmd/artifact/follow/follow.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/cli, size/XS

#258 fix(push.go): allow the push cmd to inform about the required flags
  cmd/registry/push/push.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, area/cli, area/examples

#259 fix(artifact/info): print tags in their original format
  cmd/artifact/info/info.go
  pkg/oci/repository/repository.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/M

#260 docs: update readme title according to description of root cmd
  README.md
Labels: dco-signoff: yes, lgtm, approved, kind/documentation, size/XS
