Repository falcosecurity/falcoctl, pull requests merged in 2023-11, with the labels that each got.

#339 fix(oci/puller): do not omit previous errors when returning them
  cmd/artifact/install/install.go
  internal/follower/follower.go
  pkg/oci/puller/puller.go
  pkg/oci/puller/puller_suite_test.go
  pkg/oci/puller/puller_test.go
Labels: dco-signoff: yes, lgtm, size/XXL, approved, kind/bug, area/library, area/cli, area/tests

#340 new(cmd): add artifact config command
  cmd/artifact/artifact.go
  cmd/artifact/config/config.go
  cmd/artifact/config/config_suite_test.go
  cmd/artifact/config/config_test.go
  cmd/artifact/config/doc.go
Labels: dco-signoff: yes, lgtm, approved, area/cli, area/tests, size/XL

#342 fix(tests): wait for registry to accept connections before running tests
  cmd/artifact/config/config_suite_test.go
  cmd/artifact/install/install_suite_test.go
  cmd/registry/auth/basic/basic_suite_test.go
  cmd/registry/auth/oauth/oauth_suite_test.go
  cmd/registry/pull/pull_suite_test.go
  cmd/registry/push/push_suite_test.go
  pkg/oci/pusher/pusher_suite_test.go
Labels: dco-signoff: yes, lgtm, approved, kind/flaky-test, area/tests, size/M

#341 update(Makefile): do not error if file does not exist when running clean target
  Makefile
Labels: dco-signoff: yes, lgtm, approved, size/XS

#345 chore(Makefile): enforce SPDX license header in Makefile `fmt` target.
  Makefile
Labels: dco-signoff: yes, lgtm, approved, kind/bug, size/XS

#346 bugpatching issue 344 vulnerabilities including GHSA-m425-mq94-257g
  build/Dockerfile
Labels: dco-signoff: yes, lgtm, approved, kind/bug, size/XS

#350 tests(artifact/config): add new tests for the --platform flag
  cmd/artifact/config/config_test.go
Labels: dco-signoff: yes, lgtm, approved, area/tests, size/M

#343 new: driver command
  cmd/artifact/install/install.go
  cmd/driver/cleanup/cleanup.go
  cmd/driver/cleanup/doc.go
  cmd/driver/config/config.go
  cmd/driver/config/doc.go
  cmd/driver/driver_linux.go
  cmd/driver/driver_others.go
  cmd/driver/install/doc.go
  cmd/driver/install/install.go
  cmd/driver/printenv/doc.go
  cmd/driver/printenv/printenv.go
  cmd/root.go
  cmd/root_test.go
  go.mod
  go.sum
  internal/config/config.go
  internal/cosign/verify.go
  internal/follower/follower.go
  internal/utils/extract.go
  internal/utils/file.go
  pkg/driver/distro/amzn.go
  pkg/driver/distro/bottlerocket.go
  pkg/driver/distro/centos.go
  pkg/driver/distro/cos.go
  pkg/driver/distro/debian.go
  pkg/driver/distro/distro.go
  pkg/driver/distro/flatcar.go
  pkg/driver/distro/generic.go
  pkg/driver/distro/minikube.go
  pkg/driver/distro/rhel.go
  pkg/driver/distro/talos.go
  pkg/driver/distro/ubuntu.go
  pkg/driver/kernel/kernel.go
  pkg/driver/type/bpf.go
  pkg/driver/type/kmod.go
  pkg/driver/type/modernbpf.go
  pkg/driver/type/type.go
  pkg/options/common.go
  pkg/options/driver.go
  pkg/options/enum.go
Labels: dco-signoff: yes, lgtm, size/XXL, approved, kind/feature, area/library, area/cli

#359 update(gha): upgrade slsa generator to v1.9.0
  .github/workflows/release.yaml
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/XS

#360 chore(pkg/driver): improved error message when err is nil.
  pkg/driver/distro/distro.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/library, size/XS

#361 chore(pkg/driver): do not fail if /sys/kernel/debug fails to be mounted.
  go.mod
  go.sum
  pkg/driver/type/bpf.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/cleanup, area/library
