Repository falcosecurity/falcoctl, pull requests merged in 2023-05, with the labels that each got.

#279 chore(oci): more clear error on wrong type
  pkg/oci/puller/puller.go
  pkg/oci/types.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/cleanup, area/cli

#280 fix: check directory existance iff necessary
  cmd/artifact/follow/follow.go
  cmd/artifact/install/install.go
  internal/follower/follower.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/M

#282 fix(cmd/registry/pull): updated help message
  cmd/registry/pull/pull.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, kind/documentation, area/cli

#283 chore(makefile): add clean target and update phony targets
  Makefile
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/cleanup, area/cli, area/tests

#286 add slsa provenance for binaries and sign container images
  .github/workflows/docker-image.yaml
  .github/workflows/release.yaml
Labels: dco-signoff: yes, lgtm, size/L, approved, kind/feature

#292 chore(falcoctl): bump oras-go to v2.2.0
  go.mod
  go.sum
Labels: dco-signoff: yes, size/S, lgtm, approved, area/library

#296 fix(cmd/registry/auth/basic): removed default oci registry
  cmd/registry/auth/basic/basic.go
  pkg/oci/constants.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/cleanup, area/cli

#298 cleanup(cmd): remove leftover code in install and follow commands
  cmd/artifact/follow/follow.go
  cmd/artifact/install/install.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/cli, size/M
