Repository falcosecurity/falcoctl, pull requests merged in 2023-08, with the labels that each got.

#310 fix(cmd/push): correctly push artifacts to ECR registry
  pkg/oci/pusher/pusher.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, area/cli

#312 refactor: rename options dropping suffix
  cmd/artifact/artifact.go
  cmd/artifact/follow/follow.go
  cmd/artifact/info/info.go
  cmd/artifact/install/install.go
  cmd/artifact/list/artifact_list.go
  cmd/artifact/search/artifact_search.go
  cmd/cli_test.go
  cmd/cmd_suite_test.go
  cmd/index/add/add.go
  cmd/index/index.go
  cmd/index/list/list.go
  cmd/index/remove/remove.go
  cmd/index/update/update.go
  cmd/registry/auth/auth.go
  cmd/registry/auth/basic/basic.go
  cmd/registry/auth/gcp/gcp.go
  cmd/registry/auth/oauth/oauth.go
  cmd/registry/pull/pull.go
  cmd/registry/push/push.go
  cmd/registry/registry.go
  cmd/root.go
  cmd/version/version.go
  cmd/version/version_test.go
  pkg/options/artifact.go
  pkg/options/common.go
  pkg/options/registry.go
Labels: dco-signoff: yes, lgtm, size/L, approved, kind/cleanup, area/library, area/cli

#317 fix(build): use golang 1.21 and up to date alpine image in dockerfile.
  build/Dockerfile
Labels: dco-signoff: yes, lgtm, approved, kind/bug, size/XS

#318 fix(cmd): correctly propagate signal handler to sub-commands
  cmd/root.go
  main.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, area/cli
