Repository falcosecurity/falcoctl, pull requests merged in 2023-09, with the labels that each got.

#323 fix(follow): pass full repo+sha to the signature verification function
  internal/follower/follower.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, area/library

#324 fix(cmd/artifact/follow): colored output despite `--disable-styling`
  pkg/output/output.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/XS

#322 update(docs): add FALCOCTL_ARTIFACT_NOVERIFY
  README.md
Labels: dco-signoff: yes, lgtm, approved, kind/documentation, area/cli, size/XS
