Repository falcosecurity/falcoctl, pull requests merged in 2023-12, with the labels that each got.

#362 new(cmd/driver,pkg/options,internal/config): added `driver config` cmd tests
  cmd/driver/config/config.go
  cmd/driver/config/config_suite_test.go
  cmd/driver/config/config_test.go
  cmd/driver/printenv/printenv.go
  internal/config/config.go
  pkg/options/driver.go
Labels: dco-signoff: yes, lgtm, size/L, approved, kind/cleanup, area/cli, area/tests

#368 fix(cmd/driver): fixed segfault in driver config command.
  cmd/driver/config/config.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, area/cli

#369 fix(pkg,cmd): eBPF probe must be symlinked under /root/.falco/falco-bpf.o
  cmd/driver/install/install.go
  pkg/driver/type/bpf.go
  pkg/driver/type/kmod.go
  pkg/driver/type/modernbpf.go
  pkg/driver/type/type.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/library, area/cli, size/M

#374 new(cmd/driver): added more driver commands tests.
  cmd/driver/cleanup/cleanup_suite_test.go
  cmd/driver/cleanup/cleanup_test.go
  cmd/driver/install/install_suite_test.go
  cmd/driver/install/install_test.go
  cmd/driver/printenv/printenv_suite_test.go
  cmd/driver/printenv/printenv_test.go
Labels: dco-signoff: yes, lgtm, size/XXL, approved, kind/cleanup, area/tests

#377 update(ci): upgrade cosign-installer to v3.3.0
  .github/workflows/docker-image.yaml
Labels: dco-signoff: yes, lgtm, approved, kind/bug, size/XS
