Repository falcosecurity/falcoctl, pull requests merged in 2023-03, with the labels that each got.

#262 chore(cmd/artifact/install): fix description
  cmd/artifact/install/install.go
Labels: dco-signoff: yes, lgtm, approved, kind/documentation, area/cli, area/examples, size/XS

#271 update(Makefile): bump golangci-lint version to 1.52.2
  Makefile
Labels: dco-signoff: yes, lgtm, approved, size/XS

#274 feat(index/remove): add output messages for index remove command
  cmd/index/remove/remove.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/feature, area/cli
