Repository falcosecurity/falcoctl, pull requests merged in 2024-11, with the labels that each got.

#671 fix(pkg/oci): fix Tags pagination support.
  pkg/oci/repository/repository.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/library, size/XS

#672 update(go): bumped driverkit dep to v0.20.4.
  go.mod
  go.sum
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, size/XS

#659 fix(auth/gcp): ensure correct OAuth scope for Artifact Registry with service account
  internal/login/gcp/gcp.go
  pkg/oci/authn/gcp.go
Labels: dco-signoff: yes, lgtm, approved, size/XS
