Repository falcosecurity/falcoctl, pull requests merged in 2024-07, with the labels that each got.

#597 chore(cmd/driver,pkg/driver): allow to disable kernel headers automatic download
  cmd/driver/driver_linux.go
  cmd/driver/install/install.go
  cmd/driver/install/install_test.go
  pkg/driver/distro/distro.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/cleanup, area/cli

#598 chore(go.mod): bump go version to 1.22.5
  go.mod
Labels: dco-signoff: yes, lgtm, approved, size/XS

#599 feat(dockerfile): use distroless image for falcoctl docker image
  build/Dockerfile
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/feature

#611 Feat: Add support for S3 index storage backend
  README.md
  go.mod
  pkg/index/fetch/fetch.go
  pkg/index/fetch/s3/doc.go
  pkg/index/fetch/s3/fetcher.go
  pkg/index/fetch/s3/types.go
Labels: dco-signoff: yes, lgtm, size/L, approved, kind/feature, area/library

#612 chore(Makefile): add .PHONY to falcoctl target
  Makefile
Labels: dco-signoff: yes, lgtm, approved, size/XS

#613 fix(push): use basename for artifacts when compressed in tar.gz
  cmd/registry/push/push.go
  internal/utils/compress.go
  internal/utils/compress_test.go
  pkg/driver/type/modernbpf.go
Labels: dco-signoff: yes, lgtm, approved, area/library, area/cli, size/M

#615 update(.goreleaser): bump version to v2
  .goreleaser.yml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#614 update(OWNERS): add loresuso to approvers
  OWNERS
Labels: dco-signoff: yes, lgtm, approved, size/XS
