Repository falcosecurity/falcoctl, pull requests merged in 2024-05, with the labels that each got.

#543 add new boolean arg for 'registry push' --add-floating-tags, it will auto add the tags for the major and the minor versions
  README.md
  cmd/registry/push/push.go
  cmd/registry/push/push_rulesfiles_test.go
  cmd/registry/push/push_test.go
  pkg/options/artifact.go
Labels: dco-signoff: yes, lgtm, approved, kind/feature, area/cli, size/M

#550 cleanup(cmd,pkg): moved `enum` to its own package.
  pkg/enum/doc.go
  pkg/enum/enum.go
  pkg/enum/enum_test.go
  pkg/options/common.go
  pkg/options/driver.go
  pkg/output/logFormat.go
  pkg/output/logFormat_test.go
  pkg/output/logLevel.go
  pkg/output/logLevel_test.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/library, size/M

#551 fix(pkg/driver): create envmap if nil since driverkit expects it.
  pkg/driver/distro/distro.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/library, size/XS

#552 chore(cmd/driver): remove redundant log.
  cmd/driver/install/install.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/cli, size/XS

#554 feat: Add --platform option to artifact/install
  cmd/artifact/install/constants.go
  cmd/artifact/install/install.go
  cmd/artifact/install/install_test.go
Labels: dco-signoff: yes, lgtm, approved, kind/failing-test, kind/feature, area/cli, size/M

#555 feat: Add file backend to fetcher
  README.md
  pkg/index/fetch/fetch.go
  pkg/index/fetch/file/doc.go
  pkg/index/fetch/file/fetcher.go
  pkg/index/fetch/file/fetcher_test.go
Labels: dco-signoff: yes, lgtm, size/L, approved, kind/feature

#561 chore(cmd,internal): expose FALCOCTL_DRIVER_CONFIG_UPDATE_FALCO env var.
  cmd/driver/config/config.go
  internal/config/config.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/cleanup, area/cli

#562 chore(pkg/driver): restored `uek` kernel check.
  pkg/driver/distro/distro_test.go
  pkg/driver/distro/oracle.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/library, size/M
