Repository falcosecurity/falcoctl, pull requests merged in 2024-03, with the labels that each got.

#467 feat(cmd/push): parse requirements and deps from rulesfile
  cmd/registry/push/push.go
  cmd/registry/push/push_suite_test.go
  cmd/registry/push/push_test.go
  go.mod
  go.sum
  pkg/test/data/rules.yaml
  pkg/test/data/rulesWithoutReqAndDeps.yaml
  pkg/test/filesystem.go
Labels: dco-signoff: yes, lgtm, size/XXL, approved, area/cli, area/tests

#478 update(cmd): bumped oras to v.2.4.0.
  cmd/registry/pull/pull_test.go
  cmd/registry/push/push_test.go
  go.mod
  go.sum
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/cleanup

#479 fix(registry/push): correctly remove temporary dir
  cmd/registry/push/push.go
  internal/utils/compress.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, area/cli

#486 update(tests/push): add new tests for push command
  cmd/registry/push/push.go
  cmd/registry/push/push_plugins_test.go
  cmd/registry/push/push_rulesfiles_test.go
  cmd/registry/push/push_test.go
  internal/utils/compress.go
  internal/utils/compress_test.go
Labels: dco-signoff: yes, lgtm, size/XXL, approved, area/tests

#495 chore(docco): Add Homebrew as a MacOS install option
  README.md
Labels: dco-signoff: yes, lgtm, approved, kind/documentation, size/XS

#498 chore(cmd/push): uniform receiver for push command
  cmd/registry/push/push.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/cli, size/XS
