Repository falcosecurity/falcoctl, pull requests merged in 2024-04, with the labels that each got.

#499 fix(pkg/driver): fixup kernel headers download
  pkg/driver/distro/distro.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, kind/cleanup, area/library

#507 fix(artifact/info): filter out signature tags
  cmd/artifact/info/info.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, area/cli

#497 vote: docs(OWNERS): add alacuku (Aldo Lacuku) to approvers
  OWNERS
Labels: dco-signoff: yes, lgtm, approved, size/XS

#506 cleanup(cmd/driver): drop preview tag.
  cmd/driver/cleanup/cleanup.go
  cmd/driver/cleanup/cleanup_test.go
  cmd/driver/config/config.go
  cmd/driver/config/config_test.go
  cmd/driver/driver_linux.go
  cmd/driver/install/install.go
  cmd/driver/install/install_test.go
  cmd/driver/printenv/printenv.go
  cmd/driver/printenv/printenv_test.go
  cmd/root_test.go
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, area/cli, size/M

#508 fix(goreleaser): disable release build for windows i386.
  .goreleaser.yml
Labels: dco-signoff: yes, lgtm, approved, kind/bug, size/XS

#509 fix(install): fix missing dependency signature verification
  cmd/artifact/install/install.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug, area/cli

#515 chore(cmd): dropped leftover `experimental` for driver-loader.
  cmd/driver/cleanup/cleanup.go
  cmd/driver/cleanup/cleanup_test.go
  cmd/driver/config/config.go
  cmd/driver/config/config_test.go
  cmd/driver/driver_linux.go
  cmd/driver/install/install.go
  cmd/driver/install/install_test.go
  cmd/driver/printenv/printenv.go
  cmd/driver/printenv/printenv_test.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/cleanup, area/cli

#520 fix: Add backend 'https' to default index
  internal/config/config.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/XS

#521 chore(internal): old ebpf probe must have lowest priority.
  cmd/driver/cleanup/cleanup_test.go
  cmd/driver/config/config_test.go
  cmd/driver/install/install_test.go
  cmd/driver/printenv/printenv_test.go
  internal/config/config.go
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/cleanup, area/library

#532 chore(deps): Bump k8s.io/apimachinery from 0.29.3 to 0.30.0
  go.mod
  go.sum
Labels: dco-signoff: yes, size/S, lgtm, approved

#533 chore(build): bump go version to 1.22
  .github/workflows/integration.yaml
  .github/workflows/lint.yaml
  .github/workflows/release.yaml
  build/Dockerfile
Labels: dco-signoff: yes, size/S, lgtm, approved
