Repository falcosecurity/falcoctl, pull requests merged in 2024-02, with the labels that each got.

#416 feat: adding support for KMS in cosign
  go.mod
  go.sum
  internal/cosign/verify.go
  internal/signature/signature.go
  pkg/index/index/index.go
Labels: dco-signoff: yes, lgtm, size/L, approved, area/cli

#417 bump github.com/opencontainers/image-spec to v1.1.0-rc6
  go.mod
  go.sum
Labels: dco-signoff: yes, lgtm, approved, kind/cleanup, size/XS

#424 fix: Dead link in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dco-signoff: yes, lgtm, approved, kind/documentation, size/XS

#425 pkg/driver/flatcar: Update the script
  pkg/driver/distro/flatcar.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, kind/cleanup, area/library, size/M

#427 fix(pkg/driver): fixed generic kernelversion fixup method.
  pkg/driver/distro/generic.go
  pkg/driver/distro/generic_test.go
  pkg/driver/distro/ubuntu.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/library, size/M

#442 fix(pusher): correctly report artifact type
  cmd/registry/push/push.go
  pkg/oci/pusher/pusher.go
  pkg/oci/pusher/pusher_test.go
Labels: dco-signoff: yes, size/S, lgtm, approved, area/cli, area/tests

#448 new(CI): add ecr repository
  .github/workflows/docker-image.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#449 fix(ci): add permissions for AWS ecr
  .github/workflows/docker-image.yaml
  .github/workflows/integration.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#450 new(CI): add provenance for ecr image
  .github/workflows/release.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#452 fix(CI): properly get credentials for amazon ecr registry
  .github/workflows/release.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved, kind/bug

#453 new(ci): add provenance for main tag
  .github/workflows/integration.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#454 fix(CI): add permissions to login-to-amazon-ecr job
  .github/workflows/release.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#458 Remove extra '$' character.
  pkg/driver/type/kmod.go
Labels: dco-signoff: yes, lgtm, approved, kind/bug, area/cli, size/XS
