Repository falcosecurity/falcoctl, pull requests merged in 2025-03, with the labels that each got.

#747 fix(driver): build specific code only for linux platform
  pkg/driver/type/bpf.go
  pkg/driver/type/consts.go
  pkg/driver/type/kmod.go
  pkg/driver/type/modernbpf.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#761 chore(toolchain): bump go to version 1.23.7
  go.mod
Labels: dco-signoff: yes, lgtm, approved, size/XS

#749 chore(deps): bump oauth2 to v0.28.0
  go.mod
  go.sum
Labels: dco-signoff: yes, lgtm, approved, area/library, size/XS

#762 update(go.mod): bulk deps upgrade
  go.mod
  go.sum
Labels: dco-signoff: yes, lgtm, approved, kind/design, area/library, area/cli, area/tests, size/XL
